### ISSUE TITLE
ImportError: No module named social.apps.django_app

### ISSUE THREAD

**Issue by mastershaig** [KenanBek/django-skeleton#127]
Hey,
When I run python manage.py init this error raised. I don't know what's problem ? 

```
(venv) shaig@MacBook-Pro-Shaig:~/Documents/Fucking-projects/django-skeleton/app$ python manage.py init
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/shaig/Documents/Fucking-projects/django-skeleton/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/shaig/Documents/Fucking-projects/django-skeleton/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Users/shaig/Documents/Fucking-projects/django-skeleton/venv/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/shaig/Documents/Fucking-projects/django-skeleton/venv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/shaig/Documents/Fucking-projects/django-skeleton/venv/lib/python2.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named social.apps.django_app
```

**Comment by KenanBek** [comment]
Disable all modules related to social auth module.
